# Generated by Django 4.0.4 on 2022-05-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_student_idds_alter_student_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='co_requisites',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='credits',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='pre_requisites',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
