# Generated by Django 4.0.4 on 2022-05-13 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_courses_co_requisites_courses_credits_courses_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='idd',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='apointment',
            name='idd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.advisor'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='co_requisites',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='pre_requisites',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
