# Generated by Django 4.0.4 on 2022-05-13 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_alter_advisor_idd_alter_apointment_idd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apointment',
            name='comment',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.IntegerField(choices=[(2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=1, verbose_name='year'),
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='todo.courses')),
                ('semister', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='todo.semester')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='todo.student')),
            ],
        ),
    ]
