# Generated by Django 4.0.4 on 2022-08-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_apointment_studentid_alter_apointment_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='idd',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
